const SEARCH_MOVIE = 'SEARCH_MOVIE';
const FETCH_MOVIES = 'FETCH_MOVIES';
const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
const LOADING = 'LOADING';
const FILTER_MOVIE = 'FILTER_MOVIE';

export {
  SEARCH_MOVIE, FETCH_MOVIE_DETAILS, FETCH_MOVIES, LOADING, FILTER_MOVIE,
};
